// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocwzxovlrhbwwhmjakzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jd3p4b3Zscmhid3dobWpha3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyNDE2OTAsImV4cCI6MjA5MDgxNzY5MH0.fh-8oxTiuwsxYlcVTkd7kUKpz5-U65CMGlNxIByf_VQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});